language: julia
julia:
    - 0.7
    - 1.0
    - release
    - nightly
os:
    - linux
    - osx

after_success:
- julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
coveralls: true
codecov: true
matrix:
fast_finish: true
